version: '3.8'

services:
  contentful-cms-tester:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: contentful-cms-tester
    environment:
      - NODE_ENV=production
